CREATE TABLE market_scout_question_set (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE,
  underwriter_id bigint,
  agent varchar,
  name varchar,
  aop_deductible varchar,
  building_class varchar,
  city varchar,
  construction varchar,
  county varchar,
  cov_a varchar,
  cov_b varchar,
  cov_c varchar,
  cov_d varchar,
  cov_e varchar,
  cov_f varchar,
  distance_to_coast varchar,
  earthquake varchar,
  earthquake_deductible varchar,
  effective_date  TIMESTAMP WITH TIME ZONE,
  expiration_date  TIMESTAMP WITH TIME ZONE,
  line_of_business varchar,
  location_address varchar,
  named_insured varchar,
  number_of_stories varchar,
  occupancy varchar,
  occupancy_type varchar,
  opening_protection varchar,
  peril varchar,
  policy_form varchar,
  policy_type varchar,
  protection_class varchar,
  roof_age varchar,
  roof_anchor varchar,
  roof_covering varchar,
  roof_geometry varchar,
  roof_sheathing_attachment varchar,
  square_footage varchar,
  state varchar,
  wind_decuctable varchar,
  year_built varchar,
  year_of_update varchar,
  zip_code varchar,

  extended_replacement_cost varchar,
  water_back_up varchar,
  mold_physical_damage_liability varchar,
  ordinance_and_law_coverage varchar,
  wind_hail_deductible_type varchar,
  ho5_surcharge varchar,
  all_risk_contents varchar,
  loss_assesment varchar,
  increase_special_limit varchar,
  rc_contents varchar,
  golf_cart_coverage varchar,
  golf_cart_value varchar,
  personal_injury varchar,
  coc_theft_limit varchar,
  coc_soft_cost varchar,
  id_theft varchar,
  wc_of_employees varchar,
  sinkhole varchar,
  large_loss_ded_waiver varchar,
  burgler_alarm varchar,
  fire_alarm varchar,
  equipment_breakdown varchar,
  mandatory_evacuation varchar,
  liability_extension varchar,
  losses varchar
);